### PR TITLE
Segment

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco please review and merge if OK.

**Comment by michaelachrisco** [comment]
Looks like the branch will need to be rebased before I can merge.

**Comment by josephbridgwaterrowe** [comment]
Whoops, will fix now. Thanks :+1:

**Comment by josephbridgwaterrowe** [comment]
Closes #31

**Pull request merged**
