### PR TITLE
Vendor trait.

### LINKED ISSUE #10: Vendor details
Model and record vendor details.

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**
Add basic vendor trait details to the Entity.
 - Closes #10.

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco please review.

**Comment by michaelachrisco** [comment]
Other than those tiny changes, we should be good to go :)

**Comment by michaelachrisco** [comment]
Looks like the rebase messed up github merge.

**Comment by josephbridgwaterrowe** [comment]
Looks like it needs rebasing.

**Pull request merged**
